// tslint:disable
/**
 * Leanup Stack API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface IVersion
 */
export interface IVersion {
    /**
     * @type {number}
     * @memberof IVersion
     */
    major: number;
    /**
     * @type {number}
     * @memberof IVersion
     */
    minor: number;
    /**
     * @type {number}
     * @memberof IVersion
     */
    patch: number;
    /**
     * @type {string}
     * @memberof IVersion
     */
    text: string;
}
