sh access.sh "$1" "cli-angular"
sh access.sh "$1" "cli-angularjs"
sh access.sh "$1" "cli-aurelia"
sh access.sh "$1" "cli-inferno"
sh access.sh "$1" "cli-lit-element"
sh access.sh "$1" "cli-preact"
sh access.sh "$1" "cli-react"
sh access.sh "$1" "cli-svelte"
sh access.sh "$1" "cli-vanilla"
sh access.sh "$1" "cli-vue"
sh access.sh "$1" "cli-vue3"

sh access.sh "$1" "stack-angular"
sh access.sh "$1" "stack-angularjs"
sh access.sh "$1" "stack-aurelia"
sh access.sh "$1" "stack-inferno"
sh access.sh "$1" "stack-preact"
sh access.sh "$1" "stack-react"
sh access.sh "$1" "stack-svelte"
sh access.sh "$1" "stack-vue"
sh access.sh "$1" "stack-vue3"

sh access.sh "$1" "stack-snowpack"
sh access.sh "$1" "stack-webpack"
sh access.sh "$1" "stack"

sh access.sh "$1" "cli-addons"
sh access.sh "$1" "cli-cucumber"
sh access.sh "$1" "cli-graphql"
sh access.sh "$1" "cli-pwa"
sh access.sh "$1" "cli-webhint"

sh access.sh "$1" "form"
sh access.sh "$1" "git-hooks"

sh access.sh "$1" "material-core"
sh access.sh "$1" "material-preact"

sh access.sh "$1" "cli-core-babel"
sh access.sh "$1" "cli-core-e2e"
sh access.sh "$1" "cli-core-format"
sh access.sh "$1" "cli-core-lint"
sh access.sh "$1" "cli-core-test"
sh access.sh "$1" "cli"

sh access.sh "$1" "lib"