sh ./dist-tag.sh "$1" "cli-angular" "$2" "$3"
sh ./dist-tag.sh "$1" "cli-angularjs" "$2" "$3"
sh ./dist-tag.sh "$1" "cli-aurelia" "$2" "$3"
sh ./dist-tag.sh "$1" "cli-inferno" "$2" "$3"
sh ./dist-tag.sh "$1" "cli-lit-element" "$2" "$3"
sh ./dist-tag.sh "$1" "cli-preact" "$2" "$3"
sh ./dist-tag.sh "$1" "cli-react" "$2" "$3"
sh ./dist-tag.sh "$1" "cli-svelte" "$2" "$3"
sh ./dist-tag.sh "$1" "cli-vanilla" "$2" "$3"
sh ./dist-tag.sh "$1" "cli-vue" "$2" "$3"
sh ./dist-tag.sh "$1" "cli-vue3" "$2" "$3"

sh ./dist-tag.sh "$1" "stack-angular" "$2" "$3"
sh ./dist-tag.sh "$1" "stack-angularjs" "$2" "$3"
sh ./dist-tag.sh "$1" "stack-aurelia" "$2" "$3"
sh ./dist-tag.sh "$1" "stack-inferno" "$2" "$3"
sh ./dist-tag.sh "$1" "stack-preact" "$2" "$3"
sh ./dist-tag.sh "$1" "stack-react" "$2" "$3"
sh ./dist-tag.sh "$1" "stack-svelte" "$2" "$3"
sh ./dist-tag.sh "$1" "stack-vue" "$2" "$3"
sh ./dist-tag.sh "$1" "stack-vue3" "$2" "$3"

sh ./dist-tag.sh "$1" "stack-snowpack" "$2" "$3"
sh ./dist-tag.sh "$1" "stack-vite" "$2" "$3"
sh ./dist-tag.sh "$1" "stack-webpack" "$2" "$3"
sh ./dist-tag.sh "$1" "stack" "$2" "$3"

sh ./dist-tag.sh "$1" "cli-addons" "$2" "$3"
sh ./dist-tag.sh "$1" "cli-cucumber" "$2" "$3"
sh ./dist-tag.sh "$1" "cli-graphql" "$2" "$3"
sh ./dist-tag.sh "$1" "cli-pwa" "$2" "$3"
sh ./dist-tag.sh "$1" "cli-webhint" "$2" "$3"

sh ./dist-tag.sh "$1" "form" "$2" "$3"
sh ./dist-tag.sh "$1" "git-hooks" "$2" "$3"

sh ./dist-tag.sh "$1" "cli-core-babel" "$2" "$3"
sh ./dist-tag.sh "$1" "cli" "$2" "$3"

sh ./dist-tag.sh "$1" "lib" "$2" "$3"
