bash ./unpublish.sh "cli-angular" "$1"
bash ./unpublish.sh "cli-angularjs" "$1"
bash ./unpublish.sh "cli-aurelia" "$1"
bash ./unpublish.sh "cli-inferno" "$1"
bash ./unpublish.sh "cli-lit-element" "$1"
bash ./unpublish.sh "cli-preact" "$1"
bash ./unpublish.sh "cli-react" "$1"
bash ./unpublish.sh "cli-svelte" "$1"
bash ./unpublish.sh "cli-vanilla" "$1"
bash ./unpublish.sh "cli-vue" "$1"
bash ./unpublish.sh "cli-vue3" "$1"

bash ./unpublish.sh "stack-angular" "$1"
bash ./unpublish.sh "stack-angularjs" "$1"
bash ./unpublish.sh "stack-aurelia" "$1"
bash ./unpublish.sh "stack-inferno" "$1"
bash ./unpublish.sh "stack-lit-element" "$1"
bash ./unpublish.sh "stack-preact" "$1"
bash ./unpublish.sh "stack-react" "$1"
bash ./unpublish.sh "stack-svelte" "$1"
bash ./unpublish.sh "stack-vanilla" "$1"
bash ./unpublish.sh "stack-vue" "$1"
bash ./unpublish.sh "stack-vue3" "$1"

bash ./unpublish.sh "stack-webpack" "$1"

bash ./unpublish.sh "stack" "$1"

bash ./unpublish.sh "cli-addons" "$1"
bash ./unpublish.sh "cli-cucumber" "$1"
bash ./unpublish.sh "cli-graphql" "$1"
bash ./unpublish.sh "cli-pwa" "$1"
bash ./unpublish.sh "cli-webhint" "$1"

# bash ./unpublish.sh "features" "$1"
bash ./unpublish.sh "form" "$1"
# bash ./unpublish.sh "forms" "$1"
bash ./unpublish.sh "git-hooks" "$1"

bash ./unpublish.sh "material-core" "$1"
bash ./unpublish.sh "material-preact" "$1"
bash ./unpublish.sh "material-vanilla" "$1"

bash ./unpublish.sh "cli-core-e2e" "$1"
bash ./unpublish.sh "cli-core-format" "$1"
bash ./unpublish.sh "cli-core-lint" "$1"
bash ./unpublish.sh "cli-core-test" "$1"
bash ./unpublish.sh "cli" "$1"

bash ./unpublish.sh "lib" "$1"