bash wake-up.sh angular $1
bash wake-up.sh angularjs $1
bash wake-up.sh aurelia $1
bash wake-up.sh inferno $1
bash wake-up.sh lit-element $1
bash wake-up.sh preact $1
bash wake-up.sh react $1
bash wake-up.sh svelte $1
bash wake-up.sh vanilla $1
bash wake-up.sh vue $1
bash wake-up.sh vue3 $1