sh wake-up.sh angular $1
sh wake-up.sh angularjs $1
sh wake-up.sh aurelia $1
sh wake-up.sh inferno $1
sh wake-up.sh lit-element $1
sh wake-up.sh preact $1
sh wake-up.sh react $1
sh wake-up.sh svelte $1
sh wake-up.sh vanilla $1
sh wake-up.sh vue $1
sh wake-up.sh vue3 $1